// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using DataAccess;

#nullable disable

namespace WinFormsApp1.Migrations
{
    [DbContext(typeof(DBContext))]
    [Migration("20230123123658_AddSecondaryWeaponPartSeedDataToDB")]
    partial class AddSecondaryWeaponPartSeedDataToDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Models.Warframe", b =>
                {
                    b.Property<int>("id_warframe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_warframe"));

                    b.Property<bool>("crafted")
                        .HasColumnType("bit");

                    b.Property<string>("warframe_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_warframe");

                    b.ToTable("Warframe");
                });

            modelBuilder.Entity("WinFormsApp1.Data.MeleeWeapon", b =>
                {
                    b.Property<int>("id_meleeWeapon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_meleeWeapon"));

                    b.Property<bool>("crafted")
                        .HasColumnType("bit");

                    b.Property<string>("meleeWeapon_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_meleeWeapon");

                    b.ToTable("MeleeWeapon");
                });

            modelBuilder.Entity("WinFormsApp1.Data.PrimaryWeapon", b =>
                {
                    b.Property<int>("id_primaryWeapon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_primaryWeapon"));

                    b.Property<bool>("crafted")
                        .HasColumnType("bit");

                    b.Property<string>("primaryWeapon_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_primaryWeapon");

                    b.ToTable("PrimaryWeapon");
                });

            modelBuilder.Entity("WinFormsApp1.Data.Relic", b =>
                {
                    b.Property<int>("id_relic")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_relic"));

                    b.Property<string>("common_1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("common_2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("common_3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("rare_1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("relic_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("uncommon_1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("uncommon_2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_relic");

                    b.ToTable("Relic");
                });

            modelBuilder.Entity("WinFormsApp1.Data.SecondaryWeapon", b =>
                {
                    b.Property<int>("id_secondaryWeapon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_secondaryWeapon"));

                    b.Property<bool>("crafted")
                        .HasColumnType("bit");

                    b.Property<string>("secondaryWeapon_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_secondaryWeapon");

                    b.ToTable("SecondaryWeapon");
                });

            modelBuilder.Entity("WinFormsApp1.Data.SecondaryWeaponPart", b =>
                {
                    b.Property<int>("id_SecondaryWeaponPart")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_SecondaryWeaponPart"));

                    b.Property<string>("secondaryWeapon_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("secondaryWeapon_part1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("secondaryWeapon_part2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("secondaryWeapon_part3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("secondaryWeapon_part4")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("secondaryWeapon_part5")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_SecondaryWeaponPart");

                    b.ToTable("SecondaryWeaponPart");
                });

            modelBuilder.Entity("WinFormsApp1.Data.WarframePart", b =>
                {
                    b.Property<int>("id_warframePart")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_warframePart"));

                    b.Property<bool>("warframe_blueprint_crafted")
                        .HasColumnType("bit");

                    b.Property<bool>("warframe_blueprint_owned")
                        .HasColumnType("bit");

                    b.Property<bool>("warframe_chassis_crafted")
                        .HasColumnType("bit");

                    b.Property<bool>("warframe_chassis_owned")
                        .HasColumnType("bit");

                    b.Property<string>("warframe_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("warframe_neuroptics_crafted")
                        .HasColumnType("bit");

                    b.Property<bool>("warframe_neuroptics_owned")
                        .HasColumnType("bit");

                    b.Property<bool>("warframe_system_crafted")
                        .HasColumnType("bit");

                    b.Property<bool>("warframe_system_owned")
                        .HasColumnType("bit");

                    b.HasKey("id_warframePart");

                    b.ToTable("WarframePart");
                });
#pragma warning restore 612, 618
        }
    }
}
